version: '3'

services:
    app:
        image: xpub/xpub:${XPUB_VERSION}
        command: >
            /bin/bash -c "
                until echo > /dev/tcp/postgres/5432; do sleep 1; done
                npx pubsweet setupdb --clobber
                npx pubsweet server
            "
        ports:
            - 3000:3000
        depends_on:
            - postgres
        environment:
            NODE_ENV: development
            NODE_CONFIG: '{
                "pubsweet-client": {
                    "API_ENDPOINT": "/api"
                },
                "pubsweet-server": {
                    "secret": "somesecret"
                },
                "password-reset": {
                    "url": "localhost:3000/password-reset"
                },
                "pubsweet-component-ink-backend": {
                    "inkEndpoint": "https://demo--ink.elifesciences.org",
                    "email": "fake",
                    "password": "fake"
                }
            }'
            PGHOST: postgres
            PGUSER: xpub
    postgres:
        image: postgres:10
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: xpub
        volumes:
            - postgres-volume:/var/lib/postgresql/data
    bootstrap:
        image: bash:4.3.48
        command: >
            /usr/local/bin/bash -c "until echo > /dev/tcp/app/3000; do sleep 1; done"
        depends_on:
            - app

volumes:
    postgres-volume:
