version: '3'

services:
    app:
        image: xpub/xpub:${XPUB_VERSION}
        command: sh -c "sleep 10 && npx pubsweet server"
        ports:
            - 3000:3000
        depends_on:
            - postgres
        environment:
            NODE_ENV: development
            PGHOST: postgres
            PGUSER: xpub
    postgres:
        image: postgres:10
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: xpub
        volumes:
            - postgres-volume:/var/lib/postgresql/data

volumes:
    postgres-volume:
